### PR TITLE
Tried solving issues and make the application efficient

### PR DESCRIPTION
**Pull request by Udit-exe**
<h3>doPut Method:</h3>

ObjectMapper: An instance of ObjectMapper is used to read the request body and convert it into a Pelicula object.
Validation: Checks if the fields of the Pelicula object are valid.
Update Operation: Calls service.updatePelicula(pelicula) to update the movie record.
Response Handling: Sets the HTTP response status and message based on the outcome of the update operation.
Error Handling: Catches exceptions and sets an appropriate error response.
<hr>

<h3>updatePelicula Method:</h3>

SQL Update: Prepares and executes an SQL update statement to update the movie record.
Logging: Uses a Logger for logging operations and errors.
Resource Management: Uses a try-with-resources block to ensure the PreparedStatement is closed properly.
Error Handling: Catches SQLException and rethrows it as a RuntimeException with a custom message.
This approach ensures that your servlet handles HTTP PUT requests to update movie records effectively, with proper error handling and resource management.

### CODE REVIEW

**Comment by ayalamarcelo** [comment]
Perfect! It's done!

**Comment by Udit-exe** [comment]
Thanks for considering 🙌🏻. Hope to contribute in future too. ❤️
If you don't mind, could provide me with a appreciation letter so that I
can add it in resume. It would be really helpful.

Best regards
Udit Agrawal

**Comment by ayalamarcelo** [comment]
Find me on Linkedin!

**Comment by Udit-exe** [comment]
Done. I have sent you a connection request.

**Pull request merged**
